---
gateway:
  port: 8080
  timeout_seconds: 30

upstreams:
  user-service:
    targets:
      - host: "localhost"
        target_port: 8081
        protocol: http
      - host: "localhost"
        target_port: 8082
        protocol: http
      - host: "localhost"
        target_port: 8083
        protocol: http

endpoints:
  - path: /user
    method: GET
    upstream: user-service
    